--USE addressBook

create TABLE address(firstName VARCHAR(255)NOT NULL,lastName VARCHAR(255) NOT NULL,address VARCHAR(255) NOT NULL,City VARCHAR(100) NOT  NULL,State VARCHAR(100)NOT NULL,Zip VARCHAR(6)NOT NULL,phoneNumber VARCHAR(12) NOT NULL,Email VARCHAR(100)NOT NULL,);